commands:
  - handle: help
    info: Показать сообщение с доступными командами
    alias: info

  - handle: status
    info: Показать статус игроков за столом
    tags: in_game
    alias: info

  - handle: description
    info: Вывести информацию о ролях в текущей игре
    tags: in_game
    alias: info

  - handle: roles
    info: Вывести набор ролей на текущую игру
    tags: in_game
    alias: info

  - handle: speech
    info: Начать свою речь (только в свою очередь)
    tags: [in_game, alive, turn_ready]
    alias: speech_related

  - handle: end_speech
    info: Досрочно завершить свою речь
    tags: [in_game, alive, turn_ready]
    alias: speech_related

  - handle: join_game
    info: Присоединиться к игре
    tags: internal

  - handle: nominate
    info: Выставить игрока на голосование, возвращает клавиатуру для выбора; возможна отмена
    tags: [in_game, alive, turn_ready, valid_target]

  - handle: commit_nominate
    info: Зафиксировать выбор игрока
    tags: internal

  - handle: vote
    info: Проголосовать за игрока на голосовании, возвращает клавиатуру для выбора
    tags: [in_game, alive, turn_ready, valid_target]

  - handle: commit_vote
    info: Зафиксировать голос
    tags: internal

  - handle: balance
    info: Проголосовать за вариант разрешения баланса, возвращает клавиатуру для выбора
    tags: [in_game, alive, turn_ready, valid_target]

  - handle: commit_balance
    info: Зафиксировать выбор на балансе
    tags: internal

  - handle: open_game
    info: Открыть регистрацию на игру
    tags: [admin, no_game]

  - handle: run_game
    info: Запустить игру
    tags: [admin, ready_to_start]

  - handle: terminate_game
    info: Завершить игру
    tags: [admin, in_game]

  - handle: start_night
    info: Начать ночную фазу
    tags: [admin, in_game, right_phase]

  - handle: skip_night
    info: Завершить ночную фазу (возможно будут сделаны случайные выстрелы)
    tags: [admin, in_game, right_phase]

  - handle: mafia_chat
    info: Ночной чат мафии
    tags: internal

  - handle: night_action
    info: Обработка ночных действий
    tags: internal
