commands:
  - handle: help
    info: Выводит сообщение с доступными командами
    alias: info

  - handle: open_game
    info: Открывает регистрацию на игру
    tags: [is_admin, no_game]

  - handle: night_action
    info: Обработка ночных действий
    tags: internal
